---
title: "Primera Evaluación - Python"
subtitle: "Conceptos Básicos"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
format: live-html 
pyodide:
  packages:
    - seaborn
    - pandas
sidebar: false
engine: knitr
resources:
  - datos/mtcars.csv
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Ejercicio 1

Asigna los valores `2` y `5` a las variables `a` y `b`. Tras asignarles valores, multiplica los números.
datos
```{pyodide}
# Definición de variables
a = 2
b = 5

# Multiplicación
resultado = a * b
print(resultado)
```

## Ejercicio 2

Suma `3` más `4`, multiplícalo por 10 y asígnalo a una variable `x`. Imprime el valor de `x` con la función `print()`.

```{pyodide}
# Definición de variables
x = (3 + 4) * 10

# Imprimir el valor de x
print(x)
```

## Ejercicio 3

Crea una variable de tipo `string` (cadena de texto).

```{pyodide}
# Crear una variable de carácter
mi_texto = "Hola, Python!"

print(mi_texto)
print(type(mi_texto))
```

## Ejercicio 4

Crea una variable numérica.

```{pyodide}
# Crear una variable numérica
numero = 123.45

print(numero)
print(type(numero))
```

## Ejercicio 5

Crea una lista de números con los valores `1`, `2` y `3`. Suma los valores de la lista con la función `sum()`.

```{pyodide}
# Definición de una lista
mi_lista = [1, 2, 3]

# suma de los valores de la lista
suma_total = sum(mi_lista)
print(suma_total)
```

## Ejercicio 6

Para este ejercicio, vamos a utilizar un conjunto de datos de la librería `seaborn`. Primero, carga la librería y el conjunto de datos `iris`. Luego, explora el nombre de las columnas del DataFrame.

```{pyodide}
import seaborn as sns

# Cargar el conjunto de datos
iris = sns.load_dataset('iris')

# Explorar las columnas del conjunto de datos
nombres_columnas = iris.columns

# Imprimir el resultado
print(nombres_columnas)
```

## Ejercicio 7

Ahora, vamos a leer un archivo CSV que se encuentra en la carpeta `datos`. Lee el archivo `mtcars.csv` con la función `read_csv()` de `pandas` y asígnalo a la variable `datos_csv`. Finalmente, imprime los primeros datos con el método `head()`.

```{pyodide}
import pandas as pd

# Leer un archivo CSV
datos_csv = pd.read_csv("./datos/mtcars.csv")

# Imprimir los primeros datos
print(datos_csv.head())
```

## Ejercicio 8

Usando el DataFrame `datos_csv`, selecciona las columnas `mpg`, `cyl` y `hp`. Asigna el resultado a la variable `datos_seleccionados` e imprime los primeros datos con `head()`.

```{pyodide}
# Seleccionar columnas
datos_seleccionados = datos_csv[['mpg', 'cyl', 'hp']]

print(datos_seleccionados.head())
```

## Ejercicio 9

Contesta: ¿Cuántas variables y observaciones tiene el conjunto de datos `datos_seleccionados`?

```{pyodide}
# Número de observaciones y variables
print(datos_seleccionados.shape)
```
